name: Backup After PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  backup:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Bundle
        run: |
          git bundle create backup.bundle --all

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload To S3
        run: |
          aws s3 cp backup.bundle \
          s3://swapnil-git-backups/pr-backups/pr-${{ github.run_number }}.bundle

          